# Generated by Django 5.1.2 on 2024-10-30 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')], default=3, verbose_name='性别')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='学生头像')),
                ('name', models.CharField(help_text='学生姓名', max_length=100, verbose_name='姓名')),
                ('student_id', models.CharField(help_text='学号，必须唯一', max_length=20, unique=True, verbose_name='学号')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('class_name', models.CharField(help_text='班级名称', max_length=20, verbose_name='班级')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='出生日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='在校状态')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='导师')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='students.course', verbose_name='课程')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data ownership department')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_guardian', to=settings.AUTH_USER_MODEL, verbose_name='监护人')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
    ]
