# Generated by Django 5.1.2 on 2024-11-02 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_course_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '监护人信息',
                'verbose_name_plural': '监护人信息',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_guardian', to='students.guardian', verbose_name='监护人'),
        ),
    ]
